"""Q3 .map file exporter.

Converts AABB geometry from geometry.py into Quake III .map text format.
Each Brush (AABB) becomes 6 axis-aligned half-planes. The .map file can
be compiled to .bsp via q3map2.

Q3 .map brush format:
    {
    ( x1 y1 z1 ) ( x2 y2 z2 ) ( x3 y3 z3 ) texture xoff yoff rot xscale yscale
    ...6 planes...
    }

Each plane is defined by 3 points (CCW winding when viewed from outside).
"""

from __future__ import annotations

from bhop.geometry import Brush, MapGeometry

# Default texture for all brush faces
_TEXTURE = "common/caulk"
_TEX_PARAMS = "0 0 0 1 1"  # xoff yoff rotation xscale yscale


def _brush_to_planes(brush: Brush) -> list[str]:
    """Convert an AABB brush to 6 plane definitions.

    Each plane is 3 points. Normals (computed as (p2-p1)x(p3-p1)) point
    INWARD toward the brush center. q3map2 expects this convention.
    Returns 6 lines, one per face: +x, -x, +y, -y, +z, -z.
    """
    x0, y0, z0 = float(brush.mins[0]), float(brush.mins[1]), float(brush.mins[2])
    x1, y1, z1 = float(brush.maxs[0]), float(brush.maxs[1]), float(brush.maxs[2])

    def p(x: float, y: float, z: float) -> str:
        # Format as integer if whole, otherwise float
        def f(v: float) -> str:
            return str(int(v)) if v == int(v) else f"{v:.4f}"
        return f"( {f(x)} {f(y)} {f(z)} )"

    planes = [
        # +X face (normal pointing -X, inward): winding on x1 plane
        f"{p(x1, y0, z0)} {p(x1, y0, z1)} {p(x1, y1, z0)} {_TEXTURE} {_TEX_PARAMS}",
        # -X face (normal pointing +X, inward): winding on x0 plane
        f"{p(x0, y0, z0)} {p(x0, y1, z0)} {p(x0, y0, z1)} {_TEXTURE} {_TEX_PARAMS}",
        # +Y face (normal pointing -Y, inward): winding on y1 plane
        f"{p(x0, y1, z0)} {p(x1, y1, z0)} {p(x0, y1, z1)} {_TEXTURE} {_TEX_PARAMS}",
        # -Y face (normal pointing +Y, inward): winding on y0 plane
        f"{p(x0, y0, z0)} {p(x0, y0, z1)} {p(x1, y0, z0)} {_TEXTURE} {_TEX_PARAMS}",
        # +Z face (normal pointing -Z, inward): winding on z1 plane
        f"{p(x0, y0, z1)} {p(x0, y1, z1)} {p(x1, y0, z1)} {_TEXTURE} {_TEX_PARAMS}",
        # -Z face (normal pointing +Z, inward): winding on z0 plane
        f"{p(x0, y0, z0)} {p(x1, y0, z0)} {p(x0, y1, z0)} {_TEXTURE} {_TEX_PARAMS}",
    ]
    return planes


def export_map(
    geometry: MapGeometry,
    path: str,
    spawn_origin: tuple[float, float, float] = (0.0, 0.0, 24.0),
    map_name: str = "bhop_map",
) -> None:
    """Export MapGeometry to a Q3 .map file.

    Args:
        geometry: MapGeometry containing AABB brushes.
        path: Output file path.
        spawn_origin: Player spawn point (x, y, z). Default z=24 is
            standing height above a floor at z=0.
        map_name: Map name (used in a comment, not parsed by q3map2).
    """
    lines: list[str] = []
    lines.append(f"// Generated by bhop map_export: {map_name}")

    # worldspawn entity with all brushes
    lines.append("{")
    lines.append('"classname" "worldspawn"')

    for brush in geometry.brushes:
        lines.append("{")
        for plane_line in _brush_to_planes(brush):
            lines.append(plane_line)
        lines.append("}")

    lines.append("}")

    # info_player_deathmatch spawn point
    sx, sy, sz = spawn_origin
    lines.append("{")
    lines.append('"classname" "info_player_deathmatch"')
    lines.append(f'"origin" "{int(sx)} {int(sy)} {int(sz)}"')
    lines.append('"angle" "0"')
    lines.append("}")

    with open(path, "w") as f:
        f.write("\n".join(lines))
        f.write("\n")
